import { Task } from '@/types/task';
import { format } from 'date-fns';
import jsPDF from 'jspdf';

export const exportToPDF = (tasks: Task[]): void => {
  if (tasks.length === 0) {
    alert('No tasks to export');
    return;
  }

  const doc = new jsPDF();

  // Colors
  const primaryColor = [79, 70, 229]; // Indigo
  const textColor = [31, 41, 55]; // Gray-800
  const lightGray = [156, 163, 175]; // Gray-400

  // Title
  doc.setFontSize(24);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('ProLance Lite Work Report', 20, 30);

  // Date generated
  doc.setFontSize(10);
  doc.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
  doc.text(`Generated on ${format(new Date(), 'MMMM dd, yyyy')}`, 20, 40);

  let yPosition = 60;

  // Summary Section
  doc.setFontSize(16);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text('Summary', 20, yPosition);
  yPosition += 15;

  const totalEarnings = tasks.reduce((sum, task) => sum + (task.paid ? task.price : 0), 0);
  const totalHours = tasks.reduce((sum, task) => sum + task.actualHours, 0);
  const completedTasks = tasks.filter(task => task.status === 'done').length;
  const pendingTasks = tasks.filter(task => task.status !== 'done').length;

  doc.setFontSize(12);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  const summaryData = [
    `Total Tasks: ${tasks.length}`,
    `Completed: ${completedTasks}`,
    `Pending: ${pendingTasks}`,
    `Total Earnings: ₱${totalEarnings.toLocaleString()}`,
    `Total Hours: ${totalHours}`,
    `Avg Hourly Rate: ₱${totalHours > 0 ? (totalEarnings / totalHours).toFixed(2) : '0'}`
  ];

  summaryData.forEach((item, index) => {
    doc.text(item, 25, yPosition + (index * 8));
  });

  yPosition += summaryData.length * 8 + 20;

  // Check if we need a new page
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 30;
  }

  // Tasks Table Header
  doc.setFontSize(14);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text('Task Details', 20, yPosition);
  yPosition += 10;

  // Table headers
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  const headers = ['Task', 'Client', 'Price', 'Hours', 'Status', 'Paid'];
  const columnWidths = [60, 40, 25, 20, 25, 20];
  let xPosition = 20;

  headers.forEach((header, index) => {
    doc.text(header, xPosition, yPosition);
    xPosition += columnWidths[index];
  });

  yPosition += 8;

  // Draw header line
  doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.line(20, yPosition - 2, 190, yPosition - 2);
  yPosition += 5;

  // Task rows
  doc.setFontSize(9);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  tasks.forEach((task, index) => {
    // Check if we need a new page
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 30;

      // Repeat headers on new page
      doc.setFontSize(10);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      xPosition = 20;
      headers.forEach((header, headerIndex) => {
        doc.text(header, xPosition, yPosition);
        xPosition += columnWidths[headerIndex];
      });
      yPosition += 8;
      doc.line(20, yPosition - 2, 190, yPosition - 2);
      yPosition += 5;
      doc.setFontSize(9);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    }

    xPosition = 20;

    // Task data
    const taskData = [
      task.title.length > 20 ? task.title.substring(0, 17) + '...' : task.title,
      task.clientId.length > 15 ? task.clientId.substring(0, 12) + '...' : task.clientId,
      `₱${task.price.toLocaleString()}`,
      task.actualHours.toString(),
      task.status,
      task.paid ? 'Yes' : 'No'
    ];

    taskData.forEach((data, dataIndex) => {
      doc.text(data, xPosition, yPosition);
      xPosition += columnWidths[dataIndex];
    });

    yPosition += 6;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(lightGray[0], lightGray[1], lightGray[2]);
    doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
    doc.text('Generated by ProLance Lite', 20, 285);
  }

  // Download the PDF
  doc.save(`prolance-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};